name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
            ~/.cache/turbo
          key: turbo-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
          restore-keys: |
            turbo-${{ runner.os }}-${{ matrix.node }}-
            turbo-${{ runner.os }}-
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @abcp/types test
      - run: pnpm --filter @abcp/mcp test
      - run: pnpm --filter @abcp/evidence test
      - run: pnpm --filter @abcp/otel test
      - run: pnpm --filter @abcp/control-plane test
      - run: pnpm --filter @abcp/ui test
