name: Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'docs/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter abcp-docs build
