name: Build Provenance

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w build
      - name: Archive build outputs
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p provenance
          shopt -s nullglob
          bundles=()
          if [[ -d apps/control-plane/dist ]]; then
            bundles+=("apps/control-plane/dist")
          fi
          for dir in packages/*/dist; do
            bundles+=("$dir")
          done
          if [[ ${#bundles[@]} -eq 0 ]]; then
            echo "No dist bundles found; failing provenance step." >&2
            exit 1
          fi
          tar -czf provenance/dist-bundles.tar.gz "${bundles[@]}"
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: provenance/dist-bundles.tar.gz
