name: Build Provenance

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w build
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            dist/**/*
            packages/**/dist/**/*
