name: OpenSSF Scorecard

on:
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  security-events: read
  id-token: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard.json
          publish_results: true
      - uses: actions/upload-artifact@v4
        with:
          name: scorecard
          path: scorecard.json
